# Generated by Django 3.0.4 on 2020-03-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('logo', models.ImageField(upload_to='')),
                ('src', models.FileField(upload_to='')),
            ],
        ),
    ]
