# Generated by Django 3.1.7 on 2021-04-14 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210412_0205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='title',
        ),
        migrations.AddField(
            model_name='lesson',
            name='discipline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.discipline'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StudyDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_actual', models.DateField(verbose_name='Дата')),
                ('group', models.ManyToManyField(to='polls.SpecialGroupName')),
                ('lessons', models.ManyToManyField(to='polls.Lesson')),
            ],
            options={
                'verbose_name': 'Учебный день',
                'verbose_name_plural': 'Учебные дни',
            },
        ),
    ]
