# Generated by Django 3.0.4 on 2020-03-29 21:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200329_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateField(verbose_name='Дата публикации')),
                ('date_actual', models.DateField(verbose_name='На какую дату действует')),
                ('breakfast', models.CharField(max_length=200, verbose_name='Завтрак')),
                ('lunch', models.CharField(max_length=200, verbose_name='Обед')),
                ('dinner', models.CharField(max_length=200, verbose_name='Ужин')),
            ],
            options={
                'verbose_name': 'Расписание столовой',
                'verbose_name_plural': 'Расписание столовой',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('logo', models.ImageField(null=True, upload_to='', verbose_name='Обложка')),
                ('date_create', models.DateField(default=datetime.datetime(2020, 3, 29, 21, 8, 52, 1390), verbose_name='Дата публикации')),
                ('link_source', models.CharField(max_length=300, null=True, verbose_name='Ссылка на первоисточник')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='TimeFoLessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField(unique=True, verbose_name='№')),
                ('time_start', models.TimeField(verbose_name='Начало')),
                ('time_end', models.TimeField(verbose_name='Конец')),
            ],
        ),
        migrations.CreateModel(
            name='TimeTableLessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateField(verbose_name='Дата публикации')),
                ('date_actual', models.DateField(verbose_name='Расписание на')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('plus_info', models.TextField(null=True, verbose_name='Доп информация')),
                ('times_for_lessons', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.TimeFoLessons', verbose_name='Время')),
            ],
        ),
    ]
