# Generated by Django 3.0.4 on 2020-03-29 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_kitchenmenu_lesson_news_timefolessons_timetablelessons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date_create',
            field=models.DateField(default=datetime.datetime(2020, 3, 29, 21, 9, 44, 522696), verbose_name='Дата публикации'),
        ),
    ]
