# Generated by Django 3.1.7 on 2021-04-14 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20210414_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialgroupname',
            name='year_digit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.yearstudy'),
        ),
    ]
