# Generated by Django 3.1.7 on 2021-04-18 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20210414_2309'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupStudy',
        ),
        migrations.DeleteModel(
            name='TimeTableLessons',
        ),
    ]
