# Generated by Django 3.0.4 on 2020-03-29 21:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20200329_2109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timefolessons',
            options={'verbose_name': 'Расписание занятий', 'verbose_name_plural': 'Расписание занятий'},
        ),
        migrations.AlterField(
            model_name='news',
            name='date_create',
            field=models.DateField(default=datetime.datetime(2020, 3, 29, 21, 45, 19, 735757), verbose_name='Дата публикации'),
        ),
    ]
