# Generated by Django 3.1.7 on 2021-04-18 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20210418_0352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Пара', 'verbose_name_plural': 'Пары'},
        ),
        migrations.AlterField(
            model_name='lesson',
            name='times_for_lessons',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.timeforlessons', verbose_name='Время'),
        ),
    ]
