# Generated by Django 3.0.4 on 2020-03-29 21:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20200329_2145'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimeFoLessons',
            new_name='TimeForLessons',
        ),
        migrations.AlterModelOptions(
            name='timeforlessons',
            options={'verbose_name': 'Время занятий', 'verbose_name_plural': 'Время занятий'},
        ),
        migrations.AlterModelOptions(
            name='timetablelessons',
            options={'verbose_name': 'Расписание занятий', 'verbose_name_plural': 'Расписание занятий'},
        ),
        migrations.AlterField(
            model_name='news',
            name='date_create',
            field=models.DateField(default=datetime.datetime(2020, 3, 29, 21, 52, 21, 647982), verbose_name='Дата публикации'),
        ),
    ]
