# Generated by Django 3.1.7 on 2021-04-18 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20210418_0412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyday',
            name='group',
        ),
        migrations.AddField(
            model_name='studyday',
            name='group',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='polls.specialgroupname'),
            preserve_default=False,
        ),
    ]
