# Generated by Django 3.0.4 on 2020-04-04 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20200404_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='logo',
            field=models.ImageField(upload_to='public/Books/logo', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='book',
            name='src',
            field=models.FileField(upload_to='public/Books/file', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date_create',
            field=models.DateField(default=datetime.datetime(2020, 4, 4, 13, 40, 49, 805455), verbose_name='Дата публикации'),
        ),
    ]
