# Generated by Django 3.0.4 on 2020-04-04 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20200404_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date_create',
            field=models.DateField(default=datetime.datetime(2020, 4, 4, 14, 1, 47, 877641), verbose_name='Дата публикации'),
        ),
    ]
