# Generated by Django 3.0.5 on 2020-04-05 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20200404_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='logo',
            field=models.ImageField(upload_to='Books/logo', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='book',
            name='src',
            field=models.FileField(upload_to='Books/file', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date_create',
            field=models.DateField(default=datetime.datetime(2020, 4, 5, 9, 12, 18, 353857), verbose_name='Дата публикации'),
        ),
    ]
